source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.2.2"

gem "rubocop", "~> 1.57.2", require: false
gem "rubocop-performance", require: false
gem "standard", "~> 1.32.0"
gem "fasterer", "~> 0.11.0"
